In [188]:
import random as rand
import numpy as np
import math 

class Node:
    
    weights = []
    value = 0
    
    def __init__(self, val):  
            self.value = val
                               
    def pass_weights_in(self, w):
        self.weights = w
    
    def set_value(self, v):
        self.value = v
    
    def sigmoid(self, x):        
        return 1/(1 + np.exp(-x)) 
    
    def push_forward(self, input_layer):
        self.weights = np.random.uniform(low = -1, high = 1, size = len(input_layer.nodes))
        input_list = input_layer.gather_node_values()  
        a = sum([a*b for a,b in zip(input_list, self.weights)])
        self.value = self.sigmoid(a)
        
    def alter_weight_at_index(self, index, val):
        self.weights[index] = val
        
    def print_value(self):
        print(self.value)
        
        
class Layer:
    
    nodes = []
    
    def __init__(self, size):
        self.nodes = [Node(0) for _ in range(size)]
            
    def gather_node_values(self):
        l = [self.nodes[i].value for i in range(len(self.nodes))]
        return l
    
    def push_all_nodes(self, prev_layer): 
        for i in range(len(self.nodes)):
            self.nodes[i].push_forward(prev_layer)
    
    def assign_node_values(self, l):
        for i in range(len(self.nodes)):
            self.nodes[i].set_value(l[i])
        
    def print_layers_nodes_values(self):
        for i in range(len(self.nodes)):
            self.nodes[i].print_value()
    
    def print_layers_nodes_weights(self):
        for i in range(len(self.nodes)):
            print(self.nodes[i].weights)
        

class Mesh:
    
    layers = []
    input_layer = 0
    
    def __init__(self, input_layer, input_sizes):     
        self.input_layer = input_layer
        self.layers = [Layer(input_sizes[i]) for i in range(len(input_sizes))]
        
    def full_push_forward(self):    
        self.layers[0].push_all_nodes(input_layer)   
        for i in range(1, len(self.layers)):
            self.layers[i].push_all_nodes(self.layers[i-1])
        
    def full_print(self):
        print("Input Layer: ")
        self.input_layer.print_layers_nodes_weights()
        self.input_layer.print_layers_nodes_values()
        print("")
        
        for i in range(len(self.layers)):
            print("Layer " + str(i) + ":")
            self.layers[i].print_layers_nodes_weights()
            self.layers[i].print_layers_nodes_values()
            print("")
        
        
        
input_values = [.5, .7, -.2, -.8, .1]
input_layer = Layer(len(input_values))
input_layer.assign_node_values(input_values)

m = Mesh(input_layer, [3, 5, 2, 1])
m.full_push_forward()
m.full_print()



Input Layer: 
[]
[]
[]
[]
[]
0.5
0.7
-0.2
-0.8
0.1

Layer 0:
[0.40833286 0.62375896 0.25220198 0.41487617 0.46070277]
[ 0.17256701  0.92298066  0.40501209  0.56465143 -0.31690999]
[0.0085833  0.93220103 0.02245499 0.08260267 0.2941884 ]
0.5755487183965328
0.5418904239541681
0.6492349564465412

Layer 1:
[ 0.13787996 -0.27890053 -0.50794753]
[-0.80020849 -0.44151955 -0.65342795]
[ 0.02587338 -0.65677175 -0.98963303]
[-0.45194091  0.55028641  0.90902084]
[-0.91885435 -0.03753782  0.90224733]
0.40093898711700143
0.24526222017857371
0.2721956241514005
0.6520923286429365
0.5091449010117696

Layer 2:
[-0.61682368 -0.22965716  0.23727631 -0.08328646  0.67104215]
[ 0.47290273  0.21925901  0.3394402  -0.52014302 -0.96354095]
0.5120721325007532
0.37895454582674554

Layer 3:
[-0.2337195  -0.52135527]
0.4213457992970126

